### ISSUE TITLE
Please add a license statement

### ISSUE THREAD

**Issue by tillea** [nawrockie/dnaorg_annotate_genomes.pl#1]
Hi,
the Debian Med team considers to maintain COVID-19 relevant software inside main Debian.  However, each code needs a license and I have not found any for vadr.  Thus please add a license statement.
Thanks a lot, Andreas.

**Comment by nawrockie** [comment]
There's a LICENSE file in the top level of the git repo:
https://github.com/nawrockie/vadr/blob/master/LICENSE
Is that sufficient?

**Comment by tillea** [comment]
Ahhhh, well, I was just downloading the release tarball.  Please be so kind to include it into the next release.

**Comment by nawrockie** [comment]
Ok, can you please help me out and tell me how you downloaded the release tarball? The LICENSE should be in the 'vadr' dir after unpacking.

**Comment by tillea** [comment]
Arrgh, sorry for the noise (in both cases).  I simply downloaded old archives lacking the vadr- prefix.  So I ended up with version 0.991 which was outdated.

**Comment by nawrockie** [comment]
No problem. I used to not include the vadr- prefix, which seems to have screwed you up, so sorry about that. I'm glad it's sorted now.
