### ISSUE TITLE
Is BLAST 2.10.0 needed or will BLAST 2.9.0 work?

### ISSUE THREAD

**Issue by tseemann** [nawrockie/dnaorg_annotate_genomes.pl#10]
Is BLAST 2.10.0 needed or will BLAST 2.9.0 work?

are there any 2.10 specific needs?
2.9 supported the new v5 databases too i believe.

**Comment by nawrockie** [comment]
For vadr 1.1, BLAST 2.10.0 is required. I have not tested with BLAST 2.9.0 and don't plan to. I don't think 2.9.0 supported v5 databases but could be wrong.

**Comment by tseemann** [comment]
2.9.0 does support v5 dbs.
but i believe the _default_ creation mode in makeblastdb changed.
but blast itself supports them AFAIK
