### ISSUE TITLE
Minimum Infernal version that will work?

### ISSUE THREAD

**Issue by tseemann** [nawrockie/dnaorg_annotate_genomes.pl#11]
Will VADR work with any of the 1.1 series of Infernal?
Will 1.0 work?

**Comment by nawrockie** [comment]
Infernal 1.1.3 is needed. The vadr-install.sh script includes the dependency versions. Bio-Easel and sequip dependencies have a vadr-x.x tag on the master branch commit in those repos that correspond to a vadr release (e.g vadr-1.1 tag in sequip means that version goes with vadr 1.1). Other dependencies require looking at top of vadr-install.sh to get versions.

**Comment by tseemann** [comment]
Yes I understand install.sh has versions in it, but that doesn't always reflect the minimum version the tool will work with, so I was checking so that the bioconda team can minimize the work needed to get VADR working within the conda system. @dfornika @pvanheus

**Comment by nawrockie** [comment]
Okay, I see. Just a note of caution: all my testing is done with the versions of dependencies in the vadr-install.sh file, so using earlier versions is risky.
