### ISSUE TITLE
Installation errors: missing prereqs and Perl Inline issue

### ISSUE THREAD

**Issue by taltman** [nawrockie/dnaorg_annotate_genomes.pl#14]
I've been trying to follow the instructions for installing VADR, but I'm hitting a few issues.
Some of the errors I've been able to figure out. For example, for installing on an Amazon Linux instance on EC2, I've had to perform the following prerequisite steps:

```
	sudo yum install -y autoconf.noarch
	sudo cpanm Inline
```

Also, I find that the installer doesn't clean up after itself, so it is necessary to blow away the repo completely after each error: `rm -r vadr`.

I finally hit the following issue, which I cannot figure out:
```
make[1]: Entering directory `/home/taltman/repos/darth/third-party/vadr/Bio-Easel'
cp lib/Bio/Easel.pm blib/lib/Bio/Easel.pm
cp lib/Bio/Easel/MSA.pm blib/lib/Bio/Easel/MSA.pm
cp lib/Bio/Easel/SqFile.c blib/lib/Bio/Easel/SqFile.c
cp lib/Bio/Easel/SqFile.pm blib/lib/Bio/Easel/SqFile.pm
cp lib/Bio/Easel/Random.c blib/lib/Bio/Easel/Random.c
cp lib/Bio/Easel/SqFile.typemap blib/lib/Bio/Easel/SqFile.typemap
cp lib/Bio/Easel/Random.typemap blib/lib/Bio/Easel/Random.typemap
cp lib/Bio/Easel/Random.pm blib/lib/Bio/Easel/Random.pm
cp lib/Bio/Easel/MSA.typemap blib/lib/Bio/Easel/MSA.typemap
cp lib/Bio/Easel/MSA.c blib/lib/Bio/Easel/MSA.c
cp scripts/esl-alidepair.pl blib/script/esl-alidepair.pl
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/esl-alidepair.pl
cp scripts/esl-ssplit.pl blib/script/esl-ssplit.pl
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/esl-ssplit.pl
/usr/bin/perl -Mblib -MInline=NOISY,_INSTALL_ -MBio::Easel::SqFile -e1 0.01 blib/arch
Error. You have specified 'C' as an Inline programming language.

I currently only know about the following languages:
    Foo, foo

If you have installed a support module for this language, try deleting the
config-x86_64-linux-thread-multi-5.016003 file from the following Inline DIRECTORY, and run again:

    /home/taltman/repos/darth/third-party/vadr/Bio-Easel/_Inline

(And if that works, please file a bug report.)

 at /home/taltman/repos/darth/third-party/vadr/Bio-Easel/blib/lib/Bio/Easel/SqFile.pm line 68.
BEGIN failed--compilation aborted at /home/taltman/repos/darth/third-party/vadr/Bio-Easel/blib/lib/Bio/Easel/SqFile.pm line 74.
Compilation failed in require.
BEGIN failed--compilation aborted.
make[1]: *** [SqFile.inl] Error 255
make[1]: Leaving directory `/home/taltman/repos/darth/third-party/vadr/Bio-Easel'
```

I have no idea what this "language foo" stuff is about. I tried following the instructions to delete the specified config file for "language foo", but it doesn't change the error issued when re-running the last command.

Possibly I need to run some extra steps to load this `_Inline` Perl package with language definitions? Any help in figuring this out would be greatly appreciated! Thanks in advance for your time!

**Comment by nawrockie** [comment]
Take a look at this section the Install.md file:

https://github.com/nawrockie/vadr/blob/master/documentation/install.md#-if-installation-or-do-install-tests-localsh-fails-because-the-inline-or-lwp-perl-modules-are-not-installed

especially the part starting with 'It is possible that you have Inline installed but not for C'

I think you probably need to add
```
sudo cpanm Inline::C
```
After your line
```
sudo cpanm Inline
```

Let me know if that solves the problem or not.

**Comment by taltman** [comment]
Those changes, using cpanm instead of cpan, did the trick. Thank you for pointing out the detailed documentation!
I'm going to run VADR over some viral genomes tonight, and will provide feedback. Thanks again!
