### ISSUE TITLE
5' UTR identification?

### ISSUE THREAD

**Issue by taltman** [nawrockie/dnaorg_annotate_genomes.pl#16]
In comparing VADR vs. the NCBI annotation for SARS-CoV-2, I noticed that the NCBI annotation displays the 5' UTR, but it is missing from the VADR output:

![image](https://user-images.githubusercontent.com/2146012/85941133-d50a7a80-b8d5-11ea-89b8-67c0291814cb.png)

Perhaps I'm not parsing out the content correctly. Does VADR have a model for the 5' UTR?

**Comment by nawrockie** [comment]
VADR doesn't explicitly model 5' and 3' UTRs yet. You could try to do it by identifying the vadr-annotated start position x of the 5' most CDS  and setting the 5' UTR as 1..x-1. And similarly, identifying the vadr-annotated stop position y of the 3'-most CDS y and setting the 3' UTR as y-1..L where L is the length of the sequence being annotated.

Rfam has Sarbecovirus 5' UTR and 3' UTR models: RF03120 and RF03125 (http://rfam.xfam.org/family/RF03120 and http://rfam.xfam.org/family/RF03125)

**Comment by taltman** [comment]
Thanks for pointing out the Rfam models. Two follow-up questions for you:

1. I had assumed that all viral Rfam models for a target taxon of VADR's would be scanned for, but I guess this isn't the case in general. So which categories of Rfam models are searched for, and which ones are not?

2. Perhaps I'm being dense, but I don't see the place on the Rfam pages that you linked to, where you can download the HMM or CM model(s) for these two 'clans'. Any pointers would be greatly appreciated!

**Comment by taltman** [comment]
Please disregard my second question; I came across the Rfam blog post about the latest release, and I see the download directory for the combined CM for all of the CoV Rfams. Any help in understanding the union and intersection of these 14 models, and the ones bundled into the VADR models for CoV, would be greatly appreciated!

**Comment by nawrockie** [comment]
>I had assumed that all viral Rfam models for a target taxon of VADR's would be scanned for, but I guess this isn't the case in >general. So which categories of Rfam models are searched for, and which ones are not?

Rfam and VADR are completely separate with separate models. VADR uses a single complete genome model with individual features defined by reference coordinates in the vadr model info file (`.minfo` suffix), and when v-annotate.pl is run, each sequence is aligned, globally with respect to the sequence, to the vadr genome model and features are mapped based on the reference coordinates of the alignment. 

The stem_loop features in the vadr NC_045512 (SARS-CoV-2) model are based on Rfam annotation of some Rfam models, as listed in the `inference` qualifier in the vadr .minfo file (see below). These were added to the RefSeq annotation after manual examination of covariation support for those stem loops. 

```
$ grep stem_loop vadr-models-corona-1.1-1/NC_045512.minfo
FEATURE NC_045512 type:"stem_loop" coords:"29728..29768:+" parent_idx_str:"GBNULL" note:"Coronavirus 3' stem-loop II-like motif (s2m)" inference:"COORDINATES:profile:Rfam-release-14.1:RF00164,Infernal:1.1.2"
FEATURE NC_045512 type:"stem_loop" coords:"29609..29644:+" parent_idx_str:"GBNULL" note:"Coronavirus 3' UTR pseudoknot stem-loop 1" inference:"COORDINATES:profile:Rfam-release-14.1:RF00165,Infernal:1.1.2"
FEATURE NC_045512 type:"stem_loop" coords:"29629..29657:+" parent_idx_str:"GBNULL" note:"Coronavirus 3' UTR pseudoknot stem-loop 2" inference:"COORDINATES:profile:Rfam-release-14.1:RF00165,Infernal:1.1.2"
FEATURE NC_045512 type:"stem_loop" coords:"13476..13503:+" parent_idx_str:"GBNULL" note:"Coronavirus frameshifting stimulation element stem-loop 1" inference:"COORDINATES:profile:Rfam-release-14.1:RF00507,Infernal:1.1.2"
FEATURE NC_045512 type:"stem_loop" coords:"13488..13542:+" parent_idx_str:"GBNULL" note:"Coronavirus frameshifting stimulation element stem-loop 2" inference:"COORDINATES:profile:Rfam-release-14.1:RF00507,Infernal:1.1.2"
```
Those models are available here:
https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/coronaviridae/1.1-1/vadr-models-corona-1.1-1.tar.gz

I'm not sure if this answers your question or not...
