### ISSUE TITLE
Installation issue?

### ISSUE THREAD

**Issue by dineshkumarsrk** [nawrockie/dnaorg_annotate_genomes.pl#17]
I tried to install vadr in my ubuntu 16 LTS desktop computer, but when I tried to install the same I am ending up with an error as follows,

`ga@ga-214:~/Documents/tools/vadr-master$ sh ./vadr-install.sh linux
./vadr-install.sh: 51: [: linux: unexpected operator
./vadr-install.sh: 54: [: linux: unexpected operator
./vadr-install.sh: 57: [: t: unexpected operator
------------------------------------------------
DOWNLOADING AND BUILDING VADR 1.1
------------------------------------------------

************************************************************
IMPORTANT: BEFORE YOU WILL BE ABLE TO RUN VADR SCRIPTS,
YOU NEED TO FOLLOW THE INSTRUCTIONS OUTPUT AT THE END
OF THIS SCRIPT TO UPDATE YOUR ENVIRONMENT VARIABLES.
************************************************************

Determining current directory ... 
Set VADRINSTALLDIR as current directory (/home/ga/Documents/tools/vadr-master).
------------------------------------------------
Downloading vadr ... 
./vadr-install.sh: 82: ./vadr-install.sh: curl: not found
`
Kindly help me to fix this issue.

**Comment by nawrockie** [comment]
The install script is failing because you need to have the program 'curl' installed and in your path.

**Comment by taltman** [comment]
In case it helps, I created a Docker image for VADR: `taltman/vadr`
