### ISSUE TITLE
Found later versions of vadr inbetween sequip releases

### ISSUE THREAD

**Issue by tillea** [nawrockie/dnaorg_annotate_genomes.pl#2]
Hi,
I have found vadr-1.0.4 at top of sequip release tag page.  This is confusing for automatic version detection for Debian packaging.
Kind regards, Andreas.

**Comment by nawrockie** [comment]
I'm not sure what you mean. There is a vadr-1.0.4 tag in vadr and sequip. What exactly are you saying? The vadr-1.0.4 tag in sequip points at the sequip release that goes with vadr release 1.0.4. I tag releases of dependencies based the 'git flow' work flow: 
https://github.com/nawrockie/vadr/wiki#git-workflow---
