### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by ybdong919** [nawrockie/dnaorg_annotate_genomes.pl#23]
sh: 1: /directory/to/infernal/binaries/esl-seqstat: Exec format error

when run "v-annotate.pl" in Ubuntu 18.04.

**Comment by ybdong919** [comment]
I solved this issue: 
1. download infernal source code from its website, and then compile infernal source code. 
2. generate a folder "binaries" in infernal directory, then copy all new compiled binary files into the folder "binaries".
Note: some new complied binary files are in "src" folder, while others "esl-" files are in "easel/miniapplications/"

**Comment by nawrockie** [comment]
@ybdong919  thanks for sharing your fix to this problem. But I'm still confused as to why you had the problem in the first place. Do you know the contents of the `/directory/to/infernal/binaries` when you got the error? `esl-seqstat` should have been installed there by the `vadr-install.sh` script.

**Comment by ybdong919** [comment]
By the way, I also have to re-compiled ncbi-blast and replace the binary files in "/ncbi-blast/bin". 
 After these two fixes, VADR is working now in my ubuntu 18.04.

**Comment by nawrockie** [comment]
@ybdong919 : that's strange. One way I can imagine this happening is if you installed with`sh vadr-install.sh macosx` instead of `sh vadr-install.sh linux`, which command did you use to install? Thanks.

**Comment by ybdong919** [comment]
I did use sh vadr-install.sh linux. 
After I fix the issue about infernal and then run "v-annotate.pl ....",  other error happened. This new error indicated that syntax error of blastx. So I re-compiled NCBI-blast.  Then the running worked.
