### ISSUE TITLE
Strange handling of input sequence

### ISSUE THREAD

**Issue by standage** [nawrockie/dnaorg_annotate_genomes.pl#27]
I'm working on a SARS-Cov-2 workflow that includes VADR and I'm testing how it handles indels. I've tested on some assemblies of real samples with known indels, and VADR performs as expected. However, for unit testing purposes I've been creating mock contigs with simulated indels, and VADR's performance has been inconsistent.

Here's one case: it's the Wuhan Hu reference with an 1bp insertion at position 14321 and a 3bp deletion (CAT) at position 29124.

[wuhan-hu-2indels.txt](https://github.com/ncbi/vadr/files/5497777/wuhan-hu-2indels.txt)

VADR gets stuck at the following alignment step and consumes a lot of memory.

```
...
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Validating input                                                                        ... done. [    0.1 seconds]
# Preprocessing for N replacement: blastn classification (1 seq)                          ... done. [    0.3 seconds]
# Preprocessing for N replacement: coverage determination from blastn results (1 seq)     ... done. [    0.0 seconds]
# Replacing Ns based on results of blastn-based pre-processing                            ... done. [    0.0 seconds]
# Classifying sequences with blastn (1 seq)                                               ... done. [    0.1 seconds]
# Determining sequence coverage from blastn results (1 seq)                               ... done. [    0.0 seconds]
# Aligning sequences (NC_045512: 2 seqs)                                                  ...
```

I notice that there are two subsequences being aligned. There is a lot of missing sequence, and it doesn't seem to be related at all to the variants I introduced.

```
$ grep -c '^>' workdir/vadr/*.fa                                                                       
workdir/vadr/vadr.vadr.blastn.fa:1
workdir/vadr/vadr.vadr.cp.NC_045512.fa:1
workdir/vadr/vadr.vadr.in.fa:1
workdir/vadr/vadr.vadr.NC_045512.a.fa:1
workdir/vadr/vadr.vadr.NC_045512.a.subseq.fa:2
workdir/vadr/vadr.vadr.NC_045512.fa:1
workdir/vadr/vadr.vadr.rpn.sub.fa:0
$ grep '^>' workdir/vadr/vadr.vadr.NC_045512.a.subseq.fa 
>genome/1-14422
>genome/29026-29907
```

Any idea what's going on here?

--------

I'm using the staphb-vadr Docker image with the following command.

```
v-annotate.pl -r -s --nomisc --lowsimterm 2 --mxsize 2000 --mkey NC_045512 -f --fstlowthr 0.0 --alt_fail lowscore,fsthicnf,fstlocnf --lowsc 0.75 wuhan-hu-2indels.txt vadr
```

**Comment by nawrockie** [comment]
This has to do with the acceleration heuristic that vadr uses (-s option) for SARS-CoV-2 to limit the typical CM alignment step, which is slow and memory intensive. Briefly, it does a first pass blastn alignment and then assumes the largest ungapped HSP is correctly aligned, if there is additional sequence not included in the HSP then it aligns that with the CM. This is usually two fragments: the sequence that is 5' of the HSP and the sequence that is 3' of the HSP. In your case it is 1-14422 and 29026-29907 (with 100nt of overhanging sequence). Finally it stitches the 3 alignments (CM alignment of 5' end, ungapped blastn alignment of largest HSP, CM alignment of 3' end) together to get the final alignment. This works well for typical sequences but can be slow for sequences with indels like you are trying to test. There's a tiny amount of documentation on this: 

https://github.com/ncbi/vadr/wiki/Coronavirus-annotation#the--s-option

So what you're seeing is not unusual for sequences with indels. The annotation should be fine in the end, but it does require more time and memory for such sequences. 

If that's unclear or you have further questions let me know.

**Comment by standage** [comment]
> The annotation should be fine in the end, but it does require more time and memory for such sequences.

FWIW, I was running this on a machine with 16GB or RAM, and for me it would typically run for about 3-5 minutes at ~100% RAM utilization before failing on the alignment step. In contrast, I had no issues with increased runtime running VADR on these same genomes on a large memory node in our HPC system.

**Comment by nawrockie** [comment]
Thanks @standage . Yes, unfortunately 64Gb of RAM is recommended for SARS-CoV-2 analysis with VADR, see #3 under "How to annotate SARS-CoV-2 sequences with VADR" here: 

https://github.com/ncbi/vadr/wiki/Coronavirus-annotation

I'm closing this issue. Please let me know if you have any additional problems, and thanks for reporting this one.

**Comment by standage** [comment]
Thank you!
