### ISSUE TITLE
Cannot install using vadr-install.sh

### ISSUE THREAD

**Issue by Shufan-uga** [nawrockie/dnaorg_annotate_genomes.pl#28]
When attempting to install vadr using command ./vadr-install.sh macosx on macOS Catalina 10.15.6, the following error message came up:
-bash: ./vadr-install.sh: Permission denied

How can I solve the problem? Please let me know if you need extra information.

**Comment by nawrockie** [comment]
Try adding `sh` at the beginning of the command, like this:

```
sh ./vadr-install.sh macosx
```

If that doesn't work, make sure you have write permission in the directory you are running the command from.
