### ISSUE TITLE
> 1 CPU for v-annotate.pl

### ISSUE THREAD

**Issue by chrisgulvik** [nawrockie/dnaorg_annotate_genomes.pl#34]
I'm interested in speeding up `v-annotate.pl` by using > 1 CPU. In commit 023bdab0a8ba6bbc53f01f7cf27fc431f53e97e2 I saw you commented out the `-n` arg and in commit 0aa1d0fd81f360df2b0e12336bfcf051bb9d61ca you explicity made blast run with -num_threads 1, so perhaps you observed issues with > 1? If it's only due to users requesting more than available (e.g., confusing num threads with num CPUs) Torsten has a nice function that handles it well [here](https://github.com/tseemann/prokka/blob/master/bin/prokka#L272-L283).

Would you consider exposing CPUs as an option, where default remains 1, but allow users to request more?

**Comment by nawrockie** [comment]
Hi @chrisgulvik , the issue with multiple processors is that currently cmalign is the bottleneck in terms of speed and memory. It requires up to 64G per sequence for SARS-CoV-2 annotation, which is so high I didn't want multiple threads of cmalign running at once (N threads could require N*64G RAM). It's also the bottleneck in terms of speed, such that allowing the blastn/blastx steps to run multithreaded would have very little impact on overall running time.

That said, I'm working on a new version that reduces the memory requirement drastically, and has other improvements to allow multiple threads. I'm not exactly sure when it will be available but I can update you in a week when I should have a clearer idea.

**Comment by chrisgulvik** [comment]
Your explanation that each CPU has a RAM requirement high enough that few rigs could handle >1 CPU makes sense. If you're able to drastically reduce RAM requirement, perhaps you could re-consider the `-n <num_cpus>` arg in the future.

Thanks for all your efforts maintaining vadr!

**Comment by nawrockie** [comment]
@chrisgulvik  I told you I'd update you on progress, so just letting you know that I ran into some wrinkles I need to iron out in the new code but reducing memory and enabling multiple threads still looks promising, just delayed slightly. I'll keep you updated.

**Comment by LuisSolisLxr** [comment]
@nawrockie and I could change the amount of ram from --mxsize 64000 to --mxsize 10000 to make it more accessible?

**Comment by nawrockie** [comment]
You can, but doing that may cause some SARS-CoV-2 sequences to fail only due to the lower memory. These will fail with the UNEXPECTED_DIVERGENCE error: https://github.com/ncbi/vadr/blob/master/documentation/annotate.md#unexdivg1 

I'm working on a new version that reduces the memory requirement to < 2Gb. See earlier comments in this issue above.

**Comment by LuisSolisLxr** [comment]
@nawrockie I was able to solve the problem by executing the script without changes, even if it says --mxsize 64000, since it will use all the RAM that the machine has, without having that amount <I tried it with my pc that has 12 GB of RAM and if it worked >.

**Comment by nawrockie** [comment]
@chrisgulvik and @LuisSolisLxr :  FYI, vadr 1.2 is now available, and has a new option combination that allows multi-threading for (at least) SARS-CoV-2 processing, e.g. to run on 8 CPUs in parallel:

`--split --cpu 8 --glsearch`

See: https://github.com/ncbi/vadr/wiki/Coronavirus-annotation

RAM requirement is 2G per CPU, so 16G with `--cpu 8`

Note that `-p` is incompatible with these new options.
