### ISSUE TITLE
Problems in v-test.pl file

### ISSUE THREAD

**Issue by LuisSolisLxr** [nawrockie/dnaorg_annotate_genomes.pl#35]
Hello,
I have a problem installing vadr, when i run the following command = $VADRSCRIPTSDIR/testfiles/do-all-tests.sh 
the error is the following 
BEGIN failed - compilation aborted at /home/user/Desktop/vadr-install-dir/vadr/v-test.pl line 7.
FAIL: at least one test failed [do-issue-tests.sh]
FAIL: at least one test failed [do-all-tests.sh]
I hope you can help me solve it. Thank you.

**Comment by nawrockie** [comment]
It looks like there was a problem installing the Bio-Easel modules when you ran `vadr-install.sh`. If you reply with the output of the `vadr-install.sh` script, I may be able to help.

**Comment by LuisSolisLxr** [comment]
Hello, if I did that step of using the script and the final error is the following
 Starting "make" Stage
make[1]: Entering directory '/home/luis/Desktop/SARSCOV2/vadr-install-dir/Bio-Easel/_Inline/build/Bio/Easel/SqFile'
Running Mkbootstrap for SqFile ()
chmod 644 "SqFile.bs"
"/home/luis/anaconda3/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- SqFile.bs blib/arch/auto/Bio/Easel/SqFile/SqFile.bs 644
"/home/luis/anaconda3/bin/perl" "/home/luis/anaconda3/lib/5.32.0/ExtUtils/xsubpp"  -typemap "/home/luis/anaconda3/lib/5.32.0/ExtUtils/typemap" -typemap "/home/luis/Desktop/SARSCOV2/vadr-install-dir/Bio-Easel/blib/lib/Bio/Easel/SqFile.typemap"   SqFile.xs > SqFile.xsc
mv SqFile.xsc SqFile.c
/usr/bin/..//bin/x86_64-conda-linux-gnu-gcc -c  -iquote"/home/luis/Desktop/SARSCOV2/vadr-install-dir/Bio-Easel" -I/home/luis/Desktop/SARSCOV2/vadr-install-dir/Bio-Easel/src/easel -D_REENTRANT -D_GNU_SOURCE --sysroot=/usr/bin/..//x86_64-conda-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"0.01\" -DXS_VERSION=\"0.01\" -fPIC --sysroot=/usr/bin/..//x86_64-conda-linux-gnu/sysroot "-I/home/luis/anaconda3/lib/5.32.0/x86_64-linux-thread-multi/CORE"   SqFile.c
/bin/sh: 1: /usr/bin/..//bin/x86_64-conda-linux-gnu-gcc: not found
make[1]: *** [Makefile:335: SqFile.o] Error 127
make[1]: Leaving directory '/home/luis/Desktop/SARSCOV2/vadr-install-dir/Bio-Easel/_Inline/build/Bio/Easel/SqFile'

A problem was encountered while attempting to compile and install your Inline
C code. The command that failed was:
  "make" with error code 2

The build directory was:
/home/luis/Desktop/SARSCOV2/vadr-install-dir/Bio-Easel/_Inline/build/Bio/Easel/SqFile

To debug the problem, cd to the build directory, and inspect the output files.

 at /home/luis/Desktop/SARSCOV2/vadr-install-dir/Bio-Easel/blib/lib/Bio/Easel/SqFile.pm line 68.
	...propagated at /home/luis/perl5/lib/perl5/Inline/C.pm line 888.
BEGIN failed--compilation aborted at /home/luis/Desktop/SARSCOV2/vadr-install-dir/Bio-Easel/blib/lib/Bio/Easel/SqFile.pm line 74.
Compilation failed in require.
BEGIN failed--compilation aborted.
make: *** [Makefile:964: SqFile.inl] Error 25
I also think the error comes from BIO-Easel, but I can't fix it.
I hope you can help me. Thanks a lot.

**Comment by nawrockie** [comment]
Thanks for providing the error output but unfortunately I'm not exactly sure what's wrong. However, this line:
`/bin/sh: 1: /usr/bin/..//bin/x86_64-conda-linux-gnu-gcc: not found`
seems to indicate that the gcc compiler that you are trying to use in `/usr/bin/x86_64-conda-linux-gnu-gcc` does not exist.  Can you check to see if you have a file at that location?

The only other thing I can think of is that your Inline Perl module is not installed properly or something important has changed since you last installed it, but again I'm not sure. This page of the vadr documentation shows how to install or update Inline, so you may want to try that:

https://github.com/ncbi/vadr/blob/master/documentation/install.md#-if-installation-or-do-install-tests-localsh-fails-because-the-inline-or-lwp-perl-modules-are-not-installed

**Comment by LuisSolisLxr** [comment]
Hello,
The problem I had was that I wanted to do everything using the conda environment and it was just in the error of /usr/bin/x86_64-conda-linux-gnu-gcc, and the script did not recognize it, so I left this environment and it ran normally.
Thank you very much for your help.

**Comment by nawrockie** [comment]
You're welcome. I'm glad that you got it to work.
