### ISSUE TITLE
Feature request: Separate install script into online and offline sections

### ISSUE THREAD

**Issue by kislyuk** [nawrockie/dnaorg_annotate_genomes.pl#36]
If an APT package cannot be produced as discussed in #31, a good alternative would be to separate the install script into a portion that downloads all dependency packages, and a subsequent one that installs them. This would make packaging VADR much easier.

**Comment by nawrockie** [comment]
Hi @kislyuk , I modified the install script in the `install-iss36` branch to optionally work in two separate steps as you suggested, e.g.
```
./vadr-install.sh linux download
./vadr-install.sh build
```
Where `linux` could alternatively be `macosx`. The download step requires internet access but the build step does not (although it only works if the download step was already performed from the same directory).

The previous usage (e.g. `./vadr-install.sh linux`) still works also, and does both the download and build steps. 

Please take a look and let me know if this is sufficient to make vadr easier to package for what you're interested in. Thanks.

**Comment by kislyuk** [comment]
@nawrockie thank you so much, this is definitely an improvement! Dividing the install flow into two parts like this will allow us to download the dependency files in advance, and then install VADR into our Docker images reliably and reproducibly.

**Comment by nawrockie** [comment]
@kislyuk , good, I'm glad this will be helpful. I've merged the `install-iss36` branch with the main development branch (`develop`) so this will go into the next release of vadr. I'm not sure of the timeframe though.
