### ISSUE TITLE
install issue： mv: cannot move ‘vadr-vadr-1.2’ to ‘vadr/vadr-vadr-1.2’: Directory not empty

### ISSUE THREAD

**Issue by zhaoxvwahaha** [nawrockie/dnaorg_annotate_genomes.pl#38]
when  I run  **sh ./vadr-install.sh linux**, I got the error:
  inflating: vadr-vadr-1.2/vadr-install.sh
  inflating: vadr-vadr-1.2/vadr.pm
  inflating: vadr-vadr-1.2/vadr.qsubinfo
  inflating: vadr-vadr-1.2/vadr_seed.pm
mv: cannot move ‘vadr-vadr-1.2’ to ‘vadr/vadr-vadr-1.2’: Directory not empty

Anyone know how to solve it? I manually run **mv vadr-vadr-1.2 vadr/vadr-vadr-1.2** and then rerun the **sh ./vadr-install.sh linux** again, same error.

**Comment by zhaoxvwahaha** [comment]
@edwelker @nawrockie

**Comment by nawrockie** [comment]
@zhaoxvwahaha - my first guess is that you are not running `vadr-install.sh` from an empty directory - are you?

**Comment by zhaoxvwahaha** [comment]
@nawrockie 
I run vadr-install.sh，but because my connection dropped and I rerun the shell directly, so I need to clean all exists files then rerun it?

**Comment by nawrockie** [comment]
@zhaoxvwahaha yes, that's right. You need to remove all existing files except the installation script and then rerun the script from the beginning. That is the simplest way to fix your problem. If you continue to have trouble getting the installation script to complete, let me know and I will try to provide a different work around.
