### ISSUE TITLE
Issue in installation - reg

### ISSUE THREAD

**Issue by navajeet123** [nawrockie/dnaorg_annotate_genomes.pl#39]
I am trying to install vadr.

Command:  sh ./vadr-install.sh linux

ERROR:
cp scripts/esl-alidepair.pl blib/script/esl-alidepair.pl
"/home/navajeet/miniconda3/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/esl-alidepair.pl
cp scripts/esl-ssplit.pl blib/script/esl-ssplit.pl
"/home/navajeet/miniconda3/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/esl-ssplit.pl
"/home/navajeet/miniconda3/bin/perl" -Mblib -MInline=NOISY,_INSTALL_ -MBio::Easel::Random -e1 0.01 blib/arch
Error. You have specified 'C' as an Inline programming language.

I currently only know about the following languages:
    Foo, foo

If you have installed a support module for this language, try deleting the
config-x86_64-linux-thread-multi-5.026002 file from the following Inline DIRECTORY, and run again:

    /home/navajeet/vadr-install-dir/Bio-Easel/_Inline

(And if that works, please file a bug report.)

 at /home/navajeet/vadr-install-dir/Bio-Easel/blib/lib/Bio/Easel/Random.pm line 66.
BEGIN failed--compilation aborted at /home/navajeet/vadr-install-dir/Bio-Easel/blib/lib/Bio/Easel/Random.pm line 72.
Compilation failed in require.
BEGIN failed--compilation aborted.
make: *** [Makefile:963: Random.inl] Error 255

Can you please help me.

Regards,
Navajeet

**Comment by maximilianh** [comment]
I got the same error. The documentation says to install inline::C but then
I got another error (sent a lot to NCBI). One suggestion I got was to use
the docker container.

**Comment by nawrockie** [comment]
@navajeet123 , please try the instructions at the bottom of the section the following link brings you to:

https://github.com/ncbi/vadr/blob/master/documentation/install.md#-if-installation-or-do-install-tests-localsh-fails-because-the-inline-or-lwp-perl-modules-are-not-installed

Specifically:

It is possible that you have Inline installed but not for C, if this is the case, you might see an error message like this:
```
 Error. You have specified 'C' as an Inline programming language.

I currently only know about the following languages:

    Foo, foo
```
If this is the case, try installing Inline::C with this command:

```
cpan install Inline::C
```

**Comment by nawrockie** [comment]
@maximilianh , if you send me the full output of `vadr-install.sh` for both linux and macosx so that I can determine at what point the error occurs, I will look into it.

**Comment by maximilianh** [comment]
Oh right, sorry, we talked about this and I made it and then forgot, here
is the one for linux:
https://hgwdev-max.gi.ucsc.edu/~max/ericNawrockiNcbi/vadr-linux-build.txt

**Comment by nawrockie** [comment]
Thanks @maximilianh . Are you sure this is output from `vadr-install.sh` and not a cpan command or other command? First lines of output from `vadr-install.sh` should be: 

```
------------------------------------------------------------
DOWNLOADING AND BUILDING VADR 1.2.1
------------------------------------------------------------
```

**Comment by maximilianh** [comment]
Sorry, yes, as I said, the vadr-install.sh didn't work with the same error
message as this user reported. Then I tried cpan install inline::C and this
is the error of that.

**Comment by nawrockie** [comment]
@maximilianh  : Ok, I haven't seen this error before with cpan. I'm not sure if
you want to spend time trying to deal with the cpan installation
issues or not, given that we have also discussed on slack using the docker
image. If you do want to try to get past these cpan issues, my suggestion
would be to try to install the modules that cpan reports it
cannot locate and then rerun `cpan install inline::C`. An example
of such a module is:

Can't locate HTML/Tagset.pm in @INC (you may need to install the
HTML::Tagset module)

Here's a list of the missing modules I could find in your cpan output:
ExtUtils::Config
HTML::Tagset
HTTP::Daemon
HTTP::Date
HTTP::Headers
HTTP::Request
HTTP::Status
LWP::UserAgent
Net::SSLeay
Test::Fatal
Test::Needs
Test::RequiresInternet
Try::Tiny
URI

**Comment by maximilianh** [comment]
Hi Eric, thanks for looking into this! Oh, I start to understand, I had no
idea that cpan doesn't auto-install required dependencies, I'm used to
pip/yum/apt-get etc, so I thought that if cpan doesn't install a package,
it's probably not required.

With these keywords, I found these three cpan commands to solve the problem:

o conf prerequisites_policy 'follow'
o conf build_requires_install_policy yes
o conf commit

**Comment by nawrockie** [comment]
@maximilianh , ok, great, I'm glad you were able to solve the problem. Let me know if you have any more problems.

**Comment by maximilianh** [comment]
It didn't solve the problem. Now I'm getting other errors. I'll use the
docker container.

**Comment by nawrockie** [comment]
Ok
