### ISSUE TITLE
Documentation: vadr-map-model-coords.pl command in wiki

### ISSUE THREAD

**Issue by garfinjm** [nawrockie/dnaorg_annotate_genomes.pl#41]
Hello!

Very excited to try 1.3, being able to run vadr locally has saved me so much time.

I think the [wiki page](https://github.com/ncbi/vadr/wiki/Coronavirus-annotation#how-to-annotate-sars-cov-2-sequences-with-vadr-v13-or-later-version-1) for SARS-CoV-2 annotation has a small typo in Step 5.

The wiki says the pattern to run step 5 is \<script> \<mmap-path> \<alt.list-file> \<model>
```
$VADRSCRIPTSDIR/miniscripts/vadr-map-model-coords.pl <sarscov2-model-dir-path>/sarscov2.mmap <output-directory>/<output-alt-list-file> NC_045512
```
I think it should be \<script> \<alt.list-file> \<mmap-path> \<model>
```
$VADRSCRIPTSDIR/miniscripts/vadr-map-model-coords.pl <output-directory>/<output-alt-list-file> <sarscov2-model-dir-path>/sarscov2.mmap  NC_045512
```

Thanks for all your work on the new version,
Jake

**Comment by nawrockie** [comment]
Thanks, @garfinjm ! Fixed as of a couple of minutes ago.
