### ISSUE TITLE
 To generate GenBank format of a complete genome of SARS-CoV2 variants

### ISSUE THREAD

**Issue by shakti83kumar** [nawrockie/dnaorg_annotate_genomes.pl#42]
Dear Sir,

I have SARS-CoV2 complete genome by sequencing. I want to annotate them as like pgap in various output format for eaxample GenBank, gff and ASN.1 etc. by using vadr pipeline

Best Regards
Shakti Kumar
THSTI, INDIA

**Comment by nawrockie** [comment]
Hi, 

VADR produces output .tbl files. You can convert these to asn with the tbl2asn program:

https://www.ncbi.nlm.nih.gov/genbank/tbl2asn2/

Various other programs you can find online may be able to help you convert from asn to gff or genbank.

**Comment by shakti83kumar** [comment]
Dear Sir

Thanks for information
