### ISSUE TITLE
Error in install from Inline module

### ISSUE THREAD

**Issue by minhtrung1997** [nawrockie/dnaorg_annotate_genomes.pl#43]
I've tried download and install for the first time. I got this message when running `./vadr-install.sh linux` (also attach a 1install.log  :
[1install.log](https://github.com/ncbi/vadr/files/7591465/1install.log) 

> Warning: prerequisite Inline 0.51 not found.
> Warning: prerequisite Inline::MakeMaker 0.45 not found.
> Generating a Unix-style Makefile
> Writing Makefile for Bio::Easel
> Writing MYMETA.yml and MYMETA.json
> cp lib/Bio/Easel/Random.pm blib/lib/Bio/Easel/Random.pm
> cp lib/Bio/Easel/SqFile.c blib/lib/Bio/Easel/SqFile.c
> cp lib/Bio/Easel/SqFile.typemap blib/lib/Bio/Easel/SqFile.typemap
> cp lib/Bio/Easel/Random.c blib/lib/Bio/Easel/Random.c
> cp lib/Bio/Easel/SqFile.pm blib/lib/Bio/Easel/SqFile.pm
> cp lib/Bio/Easel/Random.typemap blib/lib/Bio/Easel/Random.typemap
> cp lib/Bio/Easel.pm blib/lib/Bio/Easel.pm
> cp lib/Bio/Easel/MSA.c blib/lib/Bio/Easel/MSA.c
> cp lib/Bio/Easel/MSA.typemap blib/lib/Bio/Easel/MSA.typemap
> cp lib/Bio/Easel/MSA.pm blib/lib/Bio/Easel/MSA.pm
> cp scripts/esl-alidepair.pl blib/script/esl-alidepair.pl
> "/home/kt/anaconda3/envs/kt/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/esl-alidepair.pl
> cp scripts/esl-ssplit.pl blib/script/esl-ssplit.pl
> "/home/kt/anaconda3/envs/kt/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/esl-ssplit.pl
> "/home/kt/anaconda3/envs/kt/bin/perl" -Mblib -MInline=NOISY,_INSTALL_ -MBio::Easel::MSA -e1 0.01 blib/arch
> Can't locate Inline.pm in @INC (you may need to install the Inline module) (@INC contains: /media/kt/data/TRUNG/2.Tool/vadr/Bio-Easel/blib/arch /media/kt/data/TRUNG/2.Tool/vadr/Bio-Easel/blib/lib /home/kt/anaconda3/envs/kt/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/kt/anaconda3/envs/kt/lib/site_perl/5.26.2 /home/kt/anaconda3/envs/kt/lib/5.26.2/x86_64-linux-thread-multi /home/kt/anaconda3/envs/kt/lib/5.26.2 .).
> BEGIN failed--compilation aborted.
> make: *** [Makefile:963: MSA.inl] Error 2
Then when I install Inline `conda install -c bioconda perl-inline`
run vadr-install.sh build to patch, another error I send in file install-build.log ! 

[vadr-install-build.log](https://github.com/ncbi/vadr/files/7591467/vadr-install-build.log)
Please give it a fix soon. Thank you

**Comment by nawrockie** [comment]
@minhtrung1997  it looks like you don't have the Inline perl module installed, see here:

https://github.com/ncbi/vadr/blob/master/documentation/install.md#-if-installation-or-do-install-tests-localsh-fails-because-the-inline-or-lwp-perl-modules-are-not-installed

**Comment by minhtrung1997** [comment]
Yeah after following your instruction, I'm able to install
[2nd_install.log](https://github.com/ncbi/vadr/files/7592695/2nd_install.log)
But when I run the test, it encounters another error 

$./do-install-tests-local.sh 
> ./do-install-tests-local.sh: line 6: /v-test.pl: No such file or directory
> ./do-install-tests-local.sh: line 12: /v-test.pl: No such file or directory
> FAIL: at least one test failed [do-install-tests-local.sh]

I run perl v-test.pl

> Can't locate Bio/Easel/MSA.pm in @INC (you may need to install the Bio::Easel::MSA module) (@INC contains: /home/kt/anaconda3/envs/kt/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/kt/anaconda3/envs/kt/lib/site_perl/5.26.2 /home/kt/anaconda3/envs/kt/lib/5.26.2/x86_64-linux-thread-multi /home/kt/anaconda3/envs/kt/lib/5.26.2 .) at v-test.pl line 7.
BEGIN failed--compilation aborted at v-test.pl line 7.

When I try install Bio::Easel::MSA through Cpan: 

> Reading '/home/kt/.cpan/Metadata'
>   Database was generated on Wed, 24 Nov 2021 00:17:02 GMT
> Warning: Cannot install Bio::Easel::MSA, don't know what it is.
> Try the command
> 
>     i /Bio::Easel::MSA/
> 
> to find objects with matching identifiers.

Please give me a recommendation

**Comment by nawrockie** [comment]
@minhtrung1997 : It looks like you need to set up environment variables as explained here:

https://github.com/ncbi/vadr/blob/master/documentation/install.md#instructions-for-setting-environment-variables-output-by-vadr-installsh

**Comment by minhtrung1997** [comment]
Thank you very much
the issues resolved but there still a bug in v-build
![image](https://user-images.githubusercontent.com/52932655/144153099-7f246095-a976-44e0-881b-f42f1e082b81.png)

Although I've already run 
cpan install Inline::C

cpan install LWP::Simple

cpan install LWP::Protocol::https

Also my virus namely ASFV need to build another protein set. Please help

**Comment by minhtrung1997** [comment]
when i check the module, it's still there
![image](https://user-images.githubusercontent.com/52932655/144156067-8c6808ae-4bc7-410c-ba88-7803595b25ce.png)

**Comment by minhtrung1997** [comment]
But when not use sudo, it's not
![image](https://user-images.githubusercontent.com/52932655/144156413-448f3586-dff9-4a35-931d-402ad5df7caf.png)

**Comment by nawrockie** [comment]
It looks like your $PERL5LIB environment variable doesn't include the necessary paths. It should include:
`$VADRBIOEASELDIR/blib/lib`
and
`$VADRBIOEASELDIR/blib/arch` 
for Bio/Easel/MSA.pm

and it looks like it should also include:
`/usr/local/share/perl/5.26.1/LWP/Protocol/https.pm`

For https.pm.

If you do `echo $PERL5LIB` it will show you the paths included.

**Comment by rpetit3** [comment]
@minhtrung1997 

Have you tried just using the version of VADR on bioconda?
```
conda create -n vadr -c conda-forge -c bioconda vadr
```

**Comment by minhtrung1997** [comment]
It work for now. Many thanks

**Comment by xiaoli-dong** [comment]
I got the same error message while I am running vadr as singularity image:

Singularity> fasta-trim-terminal-ambigs.pl 
Use of uninitialized value in subroutine entry at /usr/local/lib/perl5/5.32/site_perl/Bio/Easel/MSA.pm line 60.
Use of uninitialized value in subroutine entry at /usr/local/lib/perl5/5.32/site_perl/Bio/Easel/SqFile.pm line 59.
Can't locate sqp_seq.pm in @INC (you may need to install the sqp_seq module) (@INC contains: /usr/local/lib/perl5/5.32/site_perl /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.32/vendor_perl /usr/local/lib/perl5/vendor_perl /usr/local/lib/perl5/5.32/core_perl /usr/local/lib/perl5/core_perl .) at /usr/local/bin/fasta-trim-terminal-ambigs.pl line 17.
