### ISSUE TITLE
Error in v-build.pl on example command

### ISSUE THREAD

**Issue by halabikeren** [nawrockie/dnaorg_annotate_genomes.pl#55]
Hi dear team,

I tried to apply v-build.pl on your example accession and received an error.

**Command:** v-build.pl NC_039897 NC_039897

**Error:** ERROR in vdr_EutilsFetchToFile, problem fetching NC_039897 (undefined)

**Additional details:**
I used conda to install vadr version 1.4.
Output files: [NC_039897.zip](https://github.com/ncbi/vadr/files/7807426/NC_039897.zip)

Best,
Keren

**Comment by nawrockie** [comment]
Please try again now, there was an NCBI database connectivity issue that has been resolved.

**Comment by halabikeren** [comment]
Thank you!

Indeed, it appears to be working now.
