### ISSUE TITLE
problem with git clone corona on bitbucket

### ISSUE THREAD

**Issue by FTouzain** [nawrockie/dnaorg_annotate_genomes.pl#60]
When typing:
```
git submodule add https://bitbucket.org/nawrockie/vadr-models-corona.git vadr-model-corona
```
to clone the corona model, I obtained the following output:
```
Clonage dans '/media/dd_travail/VVV2_tools/vadr/vadr-model-corona'...
remote: Enumerating objects: 563, done.
remote: Counting objects: 100% (563/563), done.
error: échec RPC ; curl 92 HTTP/2 stream 3 was not closed cleanly before end of the underlying stream
fetch-pack: unexpected disconnect while reading sideband packet
fatal: erreur de protocole : mauvais entête de paquet
fatal: le clonage de 'https://bitbucket.org/nawrockie/vadr-models-corona.git' dans le chemin de sous-module '/media/dd_travail/VVV2_tools/vadr/vadr-model-corona' a échoué
```

French sentence 
```fatal: erreur de protocole : mauvais entête de paquet```
 means 
```fatal: protocol error: wrong packet header```

May you correct it please?
Best regards.

**Comment by nawrockie** [comment]
@FTouzain : that command works for me, though it does take a long time to complete (especially the 'compress' step). Can you reproduce this on other systems? The vadr-model-corona repo is large, which is why I put it on bitbucket and not github - not sure if that's relevant.

**Comment by FTouzain** [comment]
You are right, it worked on another system for me too. And it is working too on the one where I had the problem. Maybe a problem of vpn/proxy (even if I tried three times). My apologies for the inconvenience. Many thanks, we can close the issue.
