### ISSUE TITLE
Is there a database built for most viruses?

### ISSUE THREAD

**Issue by NailouZhang** [nawrockie/dnaorg_annotate_genomes.pl#67]
Hi Robert,

As you know, it takes a long time to create a database for just one virus. Due to the low level of similarity, the annotation of the virus may be strange. This may be caused by limited well-annotated viruses in the database. While the annotation of a virus requires a reference sequence that is highly similar to the query, is there a database built for most viruses in the vadr community?

**Comment by nawrockie** [comment]
@NailouZhang : currently there are publicly available vadr virus models for:
- some flaviviruses (https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/flaviviridae/1.2-1/vadr-models-flavi-1.2-1.tar.gz)
- some caliciviruses (https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/caliciviridae/1.2-1/vadr-models-calici-1.2-1.tar.gz)
- SARS-CoV-2 (https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/sarscov2/1.3-2/vadr-models-sarscov2-1.3-2.tar.gz)
- Monkeypox (https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/mpxv/1.4.2-1/vadr-models-mpxv-1.4.2-1.tar.gz)
- some other coronaviruses (https://ftp.ncbi.nlm.nih.gov/pub/nawrocki/vadr-models/coronaviridae/1.3-3/vadr-models-corona-1.3-3.tar.gz)

We hope to add additional models slowly, and don't expect this list to grow rapidly in the near future. The main motivation for developing a new model is usually for automatically checking sequence submissions for a particular virus to GenBank, and adding new models for this purpose often takes a long period of testing prior to putting them into automated use.

**Comment by NailouZhang** [comment]
Thank you very much for your reply and list.
