### ISSUE TITLE
Bioconda recipe

### ISSUE THREAD

**Issue by tseemann** [nawrockie/dnaorg_annotate_genomes.pl#7]
Do you have plans to build a bioconda recipe to ease installation and aid reproducibilty?

There is a community who may be able to assist with this, but i may require some patching of the code base.

**Comment by nawrockie** [comment]
I don't have plans, but don't object to someone else working on it. I will make patches on a case by case basis, but I'll generally be willing to do it unless there's some reason the patch interferes with something else. And as you may have seen in the recently closed pull request, if you do pull requests please do them to the develop branch, not master. Thanks.

**Comment by tseemann** [comment]
RE: develop branch - ok thanks
I see this now: https://github.com/nawrockie/vadr/wiki/Development-notes-and-instructions

**Comment by rpetit3** [comment]
A bit late to the party but I've started the process of adding this to Bioconda: https://github.com/bioconda/bioconda-recipes/pull/29855

**Comment by rpetit3** [comment]
VADR is now available on Bioconda
