### ISSUE TITLE
Bug: v-annotate.pl does not report cdsstopn for early in-frame stop codons in 3' truncated CDS if they are the final 3 nt of the input sequence

### ISSUE THREAD

**Issue by nawrockie** [nawrockie/dnaorg_annotate_genomes.pl#70]

**Comment by nawrockie** [comment]
Fixed as of 7f37db9
testfiles/github-issues/iss70-cdsstopn-3p tests for this bug added 763cbd5

**Comment by martin-g** [comment]
Hi @nawrockie !
Could you please check https://github.com/bioconda/bioconda-recipes/pull/45235#discussion_r1630788408 ?
I think [this commit](https://github.com/ncbi/vadr/commit/763cbd50940d5ea95315956155abc3306ef96729) added a broken symlink that cause problems with the builds.
Thanks!

**Comment by nawrockie** [comment]
@martin-g : I created a new issue for this (#78 ) and believe I have addressed it by making a new vadr release (1.6.4) that does not have the file related to the broken symlink.
