### ISSUE TITLE
Installation Documentation: vadr-install.sh download link 

### ISSUE THREAD

**Issue by jowodo** [nawrockie/dnaorg_annotate_genomes.pl#75]
Referring to the link in https://github.com/ncbi/vadr/blob/master/documentation/install.md#install
If you want to install a specific version of vadr (>0.999), the link should be 
https://raw.githubusercontent.com/ncbi/vadr/vadr-1.0/vadr-install.sh
instead of 
https://raw.githubusercontent.com/ncbi/vadr/1.0/vadr-install.sh

**Comment by nawrockie** [comment]
Thanks for catching this! Fixed in the release-1.6 branch and will be part of the next release.
