### ISSUE TITLE
Installation Issue 1.5.1

### ISSUE THREAD

**Issue by jowodo** [nawrockie/dnaorg_annotate_genomes.pl#76]
<details><summary>1. vadr-install.sh</summary>
Installing as admin
<pre>
MODULEVERSION=1.5.1
CUSTOMURL='https://raw.githubusercontent.com/ncbi/vadr/vadr-${MODULEVERSION}/vadr-install.sh'
mkdir -p $MODULEBASE/$MODULENAME/$MODULEVERSION
pushd $MODULEBASE/$MODULENAME/$MODULEVERSION
wget $CUSTOMURL
bash vadr-install.sh linux
</pre>

Testing as user
<pre>
$ $VADRSCRIPTSDIR/testfiles/do-install-tests-local.sh
# v-test.pl :: test VADR scripts [TEST SCRIPT]
# VADR 1.5.1 (Feb 2023)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# date:    Thu Oct 12 12:50:18 2023
#
# test file:                                                         /home/apps/vadr/1.5.1/vadr/testfiles/noro.r10.local.testin
# output directory:                                                  vt-n10-local
# forcing directory overwrite:                                       yes [-f]
# if output files listed in testin file already exist, remove them:  yes [--rmout]
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Parsing test file                                  ... done. [    0.0 seconds]
##teamcity[testStarted name='annotate-noro-10-local' captureStandardOutput='true']
# Running command  1 [annotate-noro-10-local]        ... ERROR, the environment variable VADRMINIMAP2DIR is not set at /home/apps/vadr/1.5.1/sequip/sqp_utils.pm line 2105.
done. [    0.2 seconds]
#       checking va-noro.r10/va-noro.r10.vadr.pass.tbl                                                                ... FAIL [output file does not exist]
#       checking va-noro.r10/va-noro.r10.vadr.fail.tbl                                                                ... FAIL [output file does not exist]
#       checking va-noro.r10/va-noro.r10.vadr.sqa                                                                     ... FAIL [output file does not exist]
#       checking va-noro.r10/va-noro.r10.vadr.sqc                                                                     ... FAIL [output file does not exist]
#       checking va-noro.r10/va-noro.r10.vadr.ftr                                                                     ... FAIL [output file does not exist]
#       checking va-noro.r10/va-noro.r10.vadr.sgm                                                                     ... FAIL [output file does not exist]
#       checking va-noro.r10/va-noro.r10.vadr.mdl                                                                     ... FAIL [output file does not exist]
#       checking va-noro.r10/va-noro.r10.vadr.alt                                                                     ... FAIL [output file does not exist]
#       checking va-noro.r10/va-noro.r10.vadr.alc                                                                     ... FAIL [output file does not exist]
##teamcity[testFailed name='annotate-noro-10-local' message='v-test.pl failure']
##teamcity[testFinished name='annotate-noro-10-local']
#
#
# FAIL: 9 of 9 files were not created correctly.
#
# Output printed to screen saved in:                   vt-n10-local.vadr.log
# List of executed commands saved in:                  vt-n10-local.vadr.cmd
# List and description of all output files saved in:   vt-n10-local.vadr.list
#
# All output files created in directory ./vt-n10-local/
#
# Elapsed time:  00:00:00.19
#                hh:mm:ss
#
[FAIL]

ERROR, at least one test FAILed

# v-test.pl :: test VADR scripts [TEST SCRIPT]
# VADR 1.5.1 (Feb 2023)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# date:    Thu Oct 12 12:50:19 2023
#
# test file:                                                         /home/apps/vadr/1.5.1/vadr/testfiles/dengue.r5.local.testin
# output directory:                                                  vt-d5-local
# forcing directory overwrite:                                       yes [-f]
# if output files listed in testin file already exist, remove them:  yes [--rmout]
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Parsing test file                                  ... done. [    0.0 seconds]
##teamcity[testStarted name='annotate-dengue-5-local' captureStandardOutput='true']
# Running command  1 [annotate-dengue-5-local]       ... ERROR, the environment variable VADRMINIMAP2DIR is not set at /home/apps/vadr/1.5.1/sequip/sqp_utils.pm line 2105.
done. [    0.2 seconds]
#       checking va-dengue.r5/va-dengue.r5.vadr.pass.tbl                                                              ... FAIL [output file does not exist]
#       checking va-dengue.r5/va-dengue.r5.vadr.fail.tbl                                                              ... FAIL [output file does not exist]
#       checking va-dengue.r5/va-dengue.r5.vadr.sqa                                                                   ... FAIL [output file does not exist]
#       checking va-dengue.r5/va-dengue.r5.vadr.sqc                                                                   ... FAIL [output file does not exist]
#       checking va-dengue.r5/va-dengue.r5.vadr.ftr                                                                   ... FAIL [output file does not exist]
#       checking va-dengue.r5/va-dengue.r5.vadr.sgm                                                                   ... FAIL [output file does not exist]
#       checking va-dengue.r5/va-dengue.r5.vadr.mdl                                                                   ... FAIL [output file does not exist]
#       checking va-dengue.r5/va-dengue.r5.vadr.alt                                                                   ... FAIL [output file does not exist]
#       checking va-dengue.r5/va-dengue.r5.vadr.alc                                                                   ... FAIL [output file does not exist]
##teamcity[testFailed name='annotate-dengue-5-local' message='v-test.pl failure']
##teamcity[testFinished name='annotate-dengue-5-local']
#
#
# FAIL: 9 of 9 files were not created correctly.
#
# Output printed to screen saved in:                   vt-d5-local.vadr.log
# List of executed commands saved in:                  vt-d5-local.vadr.cmd
# List and description of all output files saved in:   vt-d5-local.vadr.list
#
# All output files created in directory ./vt-d5-local/
#
# Elapsed time:  00:00:00.19
#                hh:mm:ss
#
[FAIL]

ERROR, at least one test FAILed

FAIL: at least one test failed [do-install-tests-local.sh]
</pre>
</details>

-------------------------------------------------------------------------------

<details><summary>2. bioconda (only found out that this option exists via #59)</summary>
as admin: 
<pre>conda create -y -n vadr-1.5.1 -c bioconda vadr=1.5.1</pre>
as user:
<pre>
$ $VADRSCRIPTSDIR/testfiles/do-install-tests-local.sh
Can't locate sqp_opts.pm in @INC (you may need to install the sqp_opts module) (@INC contains: /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/sequip-0.09/lib /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/site_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/site_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/vendor_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/vendor_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/core_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/core_perl .) at /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr/vadr.pm line 50.
Compilation failed in require at /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr/v-test.pl line 10.
Can't locate sqp_opts.pm in @INC (you may need to install the sqp_opts module) (@INC contains: /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/sequip-0.09/lib /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/site_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/site_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/vendor_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/vendor_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/core_perl /lisc/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/core_perl .) at /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr/vadr.pm line 50.
Compilation failed in require at /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr/v-test.pl line 10.
FAIL: at least one test failed [do-install-tests-local.sh]
</pre>
</details>

-------------------------------------------------------------------------------
<details><summary>3. bioconda with perl<5.32 (#59) </summary>
<pre>$ conda create -y -n vadr-1.5.1 -c bioconda vadr=1.5.1 "perl<5.32"
Channels:
 - bioconda
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package vadr-1.5.1-pl5321h031d066_2 requires perl >=5.32.1,<5.33.0a0 *_perl5, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
__ perl <5.32  is requested and can be installed;
__ vadr 1.5.1**  is not installable because it requires
   __ perl [>=5.32.1,<5.33.0a0 *_perl5|>=5.32.1,<6.0a0 *_perl5], which conflicts with any installable versions previously reported.
</pre>
</details>

-------------------------------------------------------------------------------

<details><summary>4. bioconda v1.4.1 with perl<5.32 works</summary>
Installation as admin
<pre>$ conda create -y -n vadr-1.4.1 -c bioconda vadr=1.4.1 "perl<5.32"
conda activate vadr-1.4.1
# I had to look into the download-vadr-models.sh script to find out which models can be downloaded. 
# --all option would be nice. I eventually found the info at: 
# https://raw.githubusercontent.com/nawrockie/vadr-extra/master/MODEL-VERSIONS.txt
download-vadr-models.sh calici
download-vadr-models.sh corona
download-vadr-models.sh cox1
download-vadr-models.sh flavi
download-vadr-models.sh sarscov2
</pre>
Testing as user works
<pre>$ $VADRSCRIPTSDIR/testfiles/do-install-tests-local.sh | tail -n1
Success: all tests passed [do-install-tests-local.sh]</pre>
</details>

**Comment by nawrockie** [comment]
@jowodo : for 1, the relevant error message is:

```
ERROR, the environment variable VADRMINIMAP2DIR is not set at /home/apps/vadr/1.5.1/sequip/sqp_utils.pm line 2105.
done. [    0.2 seconds]
```

There are manual steps required after running `vadr-install.sh`, including setting the `VADRMINIMAP2DIR` environment variable, as explained in the output of `vadr-install.sh`. It should also be listed in the `install.md` file but I see that it is not. I will fix this now. This environment variable is new to version 1.5.1.

For 2 through 4, @rpetit3 maintains the Bioconda recipe. Robert, I'm not sure if you have time but if so could you take a look at this? Thanks.

**Comment by rpetit3** [comment]
@jowodo in your `conda create` command can you try adding `-c conda-forge` before `-c bioconda`?

I tried locally:

```
mamba create -n test-vadr -c conda-forge -c bioconda vadr=1.5.1
conda activate test-vadr
env | grep VADR | sort
VADRBIOEASELDIR=/home/robert_petit/miniconda3/envs/test-vadr/bin
VADRBLASTDIR=/home/robert_petit/miniconda3/envs/test-vadr/bin
VADREASELDIR=/home/robert_petit/miniconda3/envs/test-vadr/bin
VADRFASTADIR=/home/robert_petit/miniconda3/envs/test-vadr/bin
VADRHMMERDIR=/home/robert_petit/miniconda3/envs/test-vadr/bin
VADRINFERNALDIR=/home/robert_petit/miniconda3/envs/test-vadr/bin
VADRINSTALLDIR=/home/robert_petit/miniconda3/envs/test-vadr
VADRMINIMAP2DIR=/home/robert_petit/miniconda3/envs/test-vadr/bin
VADRMODELDIR=/home/robert_petit/miniconda3/envs/test-vadr/share/vadr-1.5.1/vadr-models
VADRSCRIPTSDIR=/home/robert_petit/miniconda3/envs/test-vadr/share/vadr-1.5.1/vadr
VADRSEQUIPDIR=/home/robert_petit/miniconda3/envs/test-vadr/bin
VADRVERSION=1.5.1
```

**Comment by jowodo** [comment]
@nawrockie Thanks for the swift reply. Indeed, I followed the `install.md` and did not pay particular attention to the output of the `vadr-install.sh`. Setting the missing variable resolved the problem for me.

**Comment by jowodo** [comment]
@rpetit3 including the conda-forge channel leads to the same error when testing with: 
<pre>
$VADRSCRIPTSDIR/testfiles/do-install-tests-local.sh
</pre>
But all variables are set correctly. 

**Error:**
Can't locate sqp_opts.pm in @INC (you may need to install the sqp_opts module)
</pre>
It seems that this perl module is [absent from conda](https://anaconda.org/search?q=sqp)?

**Comment by nawrockie** [comment]
@jowodo : sqp_opts.pm is part of sequip :  https://anaconda.org/search?q=sequip

**Comment by jowodo** [comment]
New attempt to install vadr v1.5.1 with conda: (comments are output)
```
conda create -y -n vadr-1.5.1 -c conda-forge -c bioconda vadr=1.5.1 2&> /dev/null 
VERSION=1.5.1 
conda activate vadr-$VERSION
conda list | grep sequip
# sequip                    0.10                 hdfd78af_0    bioconda
download-vadr-models.sh calici
# Downloading current list of available VADR models...
# Can't locate sqp_opts.pm in @INC (you may need to install the sqp_opts module) (@INC contains: /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/sequip-0.09/lib /home/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/site_perl /home/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/site_perl /home/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/vendor_perl /home/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/vendor_perl /home/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/5.32/core_perl /home/app/conda/miniconda3/envs/vadr-1.5.1/lib/perl5/core_perl .) at /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr/vadr.pm line 50.
# Compilation failed in require at /home/apps/conda/miniconda3/envs/vadr-1.5.1/bin/v-annotate.pl line 13.
# Installed VADR Version: 1.5.1
# Expected VADR Version: # VADR 1.4.1 (Jan 2022)
# Please update your install of VADR to use the download script. Otherwise you will need to manually install the models.
PERL5LIB=$PERL5LIB:${CONDA_PREFIX}/share/sequip-0.10/lib/ download-vadr-models.sh calici
# Downloading current list of available VADR models...
# Installed VADR Version: 1.5.1
# Expected VADR Version: # VADR 1.4.1 (Jan 2022)
# Please update your install of VADR to use the download script. Otherwise you will need to manually install the models.
sed -i 's/1.4.1.*$/1.5.1/' ${CONDA_PREFIX}/share/vadr-1.5.1/vadr-models/MODEL-VERSIONS.txt
PERL5LIB=$PERL5LIB:${CONDA_PREFIX}/share/sequip-0.10/lib/ download-vadr-models.sh calici 
# same output because the file is downloaded https://github.com/nawrockie/vadr-extra
```
workaround: 
```
echo $PERL5LIB
# /home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr::/home/apps/conda/miniconda3/envs/vadr-1.5.1/share/sequip-0.09/lib
export PERL5LIB=$PERL5LIB:${CONDA_PREFIX}/share/sequip-0.10/lib/ 
download-vadr-models.sh calici
sed -i 's/wget --q/#wget --q/' `which  download-vadr-models.sh`
sed -i 's/1.4.1.*$/1.5.1 (Feb 2023)/' $CONDA_PREFIX/share/vadr-1.5.1/vadr-models/MODEL-VERSIONS.txt
download-vadr-models.sh calici
```
The `MODEL-VERSION.txt` should thus be updated? But then again v.1.4.1 would not be able to download the models. 
I see two options
1. use [link from tagged version](https://raw.githubusercontent.com/nawrockie/vadr-extra/vadr-1.3/MODEL-VERSIONS.txt) in `download-vadr-models.sh`. This would need tagging of 1.4.1 and 1.5.1 in the other repo 
2. move the `MODEL-VERSION.txt` file into this repo. 

I think option 2 is easier and cleaner, but I might not be aware of why the `MODEL-VERSION.txt` is in a separate repo.

**Comment by jowodo** [comment]
By pointing `PERL5LIB` to the actual location of sequip, all test passed. 
```
conda activate vadr-1.5.1
export PERL5LIB=$PERL5LIB:${CONDA_PREFIX}/share/sequip-0.10/lib/ 
$VADRSCRIPTSDIR/testfiles/do-install-tests-local.sh | grep "all tests passed"
# Success: all tests passed [do-install-tests-local.sh]
```
Again i could imagine two options: 
1. pin the sequip version for a vadr conda version (rather rigid)
2. in `$CONDA_PREFIX/share` execute `ln -s sequip-* sequip` and point `$PERL5LIB=$PERL5LIB:$CONDA_PREFIX/share/sequib/lib` instead of `$PERL5LIB=$PERL5LIB:$CONDA_PREFIX/share/sequib-0.9/lib`

**Comment by jowodo** [comment]
I found the problem with perl!!! 
the correct libdir for sequip is defined in `$CONDA_PREFIX/etc/conda/activate.d/sequip-perl5lib.sh` but then overwritten by vadr.sh: 
```
cat $CONDA_PREFIX/etc/conda/activate.d/sequip-perl5lib.sh
# export PERL5LIB=:/home/apps/conda/miniconda3/envs/vadr-1.5.1/share/sequip-0.10/lib
grep -i perl $CONDA_PREFIX/etc/conda/activate.d/vadr.sh
# export PERL5LIB=/home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr::/home/apps/conda/miniconda3/envs/vadr-1.5.1/share/sequip-0.09/lib
```
where it should be 
```
cat /lisc/app/conda/miniconda3/envs/vadr-1.5.1/etc/conda/activate.d/sequip-perl5lib.sh
# export PERL5LIB=$PERL5LIB:/home/apps/conda/miniconda3/envs/vadr-1.5.1/share/sequip-0.10/lib
grep -i perl $CONDA_PREFIX/etc/conda/activate.d/vadr.sh
# export PERL5LIB=$PERL5LIB:/home/apps/conda/miniconda3/envs/vadr-1.5.1/share/vadr-1.5.1/vadr
```
It seems that this was intended, but maybe in the conda definition double quotes instead of single quotes were used and thus `$PERL5LIB` was interpreted ...
