### ISSUE TITLE
Bioconda - 1.6.3 broken symlink

### ISSUE THREAD

**Issue by nawrockie** [nawrockie/dnaorg_annotate_genomes.pl#78]
Starting new issue from:
From @martin-g
https://github.com/ncbi/vadr/issues/70#issuecomment-2154284067 
text below

 
Hi @nawrockie !
Could you please check https://github.com/bioconda/bioconda-recipes/pull/45235#discussion_r1630788408 ?
I think [this commit](https://github.com/ncbi/vadr/commit/763cbd50940d5ea95315956155abc3306ef96729) added a broken symlink that cause problems with the builds.
Thanks!

**Comment by nawrockie** [comment]
@rpetit3 - any chance you're willing to take a look at this?

**Comment by nawrockie** [comment]
@martin-g : I just made a new release (v1.6.4) that does not include the offending file that causes the symlink issue. Otherwise 1.6.4 is essentially identical to 1.6.3.

**Comment by martin-g** [comment]
Thank you, @nawrockie !
https://github.com/bioconda/bioconda-recipes/pull/45235 builds OSX fine now!
