### ISSUE TITLE
compatibility with `-` and `.` in input assemblies

### ISSUE THREAD

**Issue by kapsakcj** [nawrockie/dnaorg_annotate_genomes.pl#79]
Hi Eric,

We've been testing VADR with some Flu genome assemblies produced by CDC's [IRMA](https://wonder.cdc.gov/amd/flu/irma/irma.html). Occasionally with lower quality samples, IRMA will output genome assemblies with `.`'s or `-`'s in the FASTA files that indicate gaps. AFAIK these are valid IUPAC characters.

When running VADR both `v-annotate.pl` or the `miniscripts/fasta-trim-terminal-ambigs.pl` scripts throw a similar error:
```
$ v-annotate.pl -v \
      --split --cpu 2 \
      --atgonly --xnocomp --nomisc --alt_fail extrant5,extrant3 --mkey flu \
      "SRR13439799.irma.consensus.fasta"

Parse failed (sequence file SRR13439799.irma.consensus.fasta):
Line 2: illegal character -


ERROR in utl_RunCommand(), the following command failed:
/opt/vadr/infernal/binaries/esl-reformat fasta SRR13439799.irma.consensus.fasta > SRR13439799.irma.consensus/SRR13439799.irma.consensus.vadr.in.fa
```

How does NCBI GenBank typically handle genome submissions where `.` or `-` are included in the nucleotide sequence? Are those sequences typically rejected?

Thanks,
Curtis

**Comment by nawrockie** [comment]
@kapsakcj : sequences with `.` or `-` indicating gaps would typically be rejected in GenBank sequence submissions (that are not alignments). If the character is unknown it should be an `N`. It's possible that characters that indicate gaps could just be removed.

**Comment by kapsakcj** [comment]
Thanks Eric, that's helpful!
