### ISSUE TITLE
Outdated MODEL-VERSIONS.txt previnting automated model download

### ISSUE THREAD

**Issue by Codes1985** [nawrockie/dnaorg_annotate_genomes.pl#82]
Hello,

Thank you very much for your ongoing development of VADR.  I love it!

I recently installed via Conda the latest release of VADR (v 1.6.4), and encountered an issue attempting to download additional models:

```shell
$ download-vadr-models.sh flu
Downloading current list of available VADR models...
Installed VADR Version: 1.6.4
Expected VADR Version: # VADR 1.4.1 (Jan 2022)
Please update your install of VADR to use the download script. Otherwise you will need to manually install the models.
``` 
I was able to overcome this error by commenting out the relevant version checking code in `download-vadr-models.sh`.  I then re-attempted to download the model, which led to the following error:

```shell
$ download-vadr-models.sh flu
Downloading current list of available VADR models...
flu is not an available VADR model, skipping...
Currently installed VADR models...
sarscov2        vadr-models-corona-1.3-2        November 2021
``` 
After investigating, I realized the script was linking to an [outdated MODEL-VERSIONS.txt](https://raw.githubusercontent.com/nawrockie/vadr-extra/master/MODEL-VERSIONS.txt), which doesn't include the latest and greatest models.

I'll install the models manually, but I wanted to bring this to your attention for future releases.

Thank you very much and take care,
Cody

**Comment by nawrockie** [comment]
@Codes1985 : thanks for bringing this to our attention! I've updated the MODEL-VERSIONS.txt file here:
https://github.com/nawrockie/vadr-extra/blob/master/MODEL-VERSIONS.txt

**Comment by Codes1985** [comment]
@nawrockie Thank you so much!  Greatly appreciate this.
