### ISSUE TITLE
Docker or singularity image

### ISSUE THREAD

**Issue by tseemann** [nawrockie/dnaorg_annotate_genomes.pl#9]
Given you have no plans for bioconda I was wondering if you have Docker or Singularity containers ready to go?

**Comment by nawrockie** [comment]
Not yet, but I am planning on working on Docker and Singularity containers soon.

**Comment by taltman** [comment]
Bump!

**Comment by taltman** [comment]
Here you go @tseemann ! DockerHub: `taltman/vadr`

**Comment by kapsakcj** [comment]
@andersgs has also put together a dockerfile for VADR 1.1 and we are adding it to the StaPH-B repository of dockerfiles & docker images. It will be up on dockerhub shortly at `staphb/vadr:latest` and `staphb/vadr:1.1`

https://github.com/StaPH-B/docker-builds/pull/136

**Comment by nawrockie** [comment]
@kapsakcj and @andersgs - thanks for contributing! I hope to have time to try to pull in dockerfiles to master before too much longer, but thanks for updating your forks too.
